require "rails_helper"
require "tempfile"

RSpec.describe "Admin portfolio backups" do
  let!(:profile) { create_portfolio_content }

  before do
    profile.avatar.attach(
      io: StringIO.new("avatar-bytes"),
      filename: "avatar.png",
      content_type: "image/png"
    )
  end

  it "exports a complete portable SQL backup and restores it transactionally" do
    result = Admin::PortfolioBackup::Export.new(profile:).call(format: :sql)

    expect(result.filename).to end_with(".sql")
    expect(result.data).to start_with("-- MY_PORTFOLIO_BACKUP_V1")
    expect(result.data).to include("INSERT INTO files")

    original_name = profile.full_name
    original_skills = profile.skills.ordered.pluck(:name)
    profile.update!(full_name: "Changed")
    profile.skills.destroy_all
    profile.skills.create!(name: "Temporary", category: "other", position: 0)
    profile.avatar.detach

    import_data(result.data, "portfolio.sql")
    restored = PortfolioProfile.current!

    expect(restored.full_name).to eq(original_name)
    expect(restored.skills.ordered.pluck(:name)).to eq(original_skills)
    expect(restored.avatar.download).to eq("avatar-bytes")
  end

  it "exports and restores the compact SQLite format" do
    result = Admin::PortfolioBackup::Export.new(profile:).call(format: :sqlite)

    expect(result.filename).to end_with(".sqlite3")
    expect(result.data).to start_with("SQLite format 3")

    profile.update!(full_name: "Changed")
    import_data(result.data, "portfolio.sqlite3")

    expect(PortfolioProfile.current!.full_name).not_to eq("Changed")
  end

  it "rejects SQL that was not generated by the application" do
    expect {
      import_data("DROP TABLE portfolio_profiles;", "malicious.sql")
    }.to raise_error(Admin::PortfolioBackup::Import::InvalidBackup)
  end

  def import_data(data, filename)
    Tempfile.create([ "portfolio", File.extname(filename) ]) do |file|
      file.binmode
      file.write(data)
      file.rewind
      upload = ActionDispatch::Http::UploadedFile.new(
        tempfile: file,
        filename:,
        type: "application/octet-stream"
      )
      Admin::PortfolioBackup::Import.new(upload:).call
    end
  end
end
